project:
  type: website
  output-dir: docs
  resources:
    - images/logo-site.png
    - fonts/

website:
  title: "Mattéo Lanoë | Doctoral Candidate in Sociology"
  site-url: "https://matteolanoe.github.io"
  description: >
    Doctorant en sociologie au CRIS (Sciences Po) & à l'INED. PhD Candidate in Sociology.
    Recherches / Research : Syndrome post-infectieux (Post-infectious syndromes), Covid long (Long Covid),
    Post-Covid-19 Symptoms, Sociologie de la santé (Medical Sociology, Sociology of Health and Illness, Sociology of Diseases), 
    Inégalités sociales de santé (Social inequalities in health),
    Corps & Maladies (Body & Illness), Virus, Sociologie économique (Economic Sociology),
    Dispositions, Épidémiologie sociale (Social Epidemiology), Méthodes qualitatives (Qualitative methods),
    Cohorte ComPaRe, Thèse, Sociologie, France.
  favicon: images/logo-site.png
  
  open-graph:
    description: "Mattéo Lanoë | Doctoral Candidate in Sociology"
    image: images/logo-site.png  # Ou une image spécifique format rectangulaire
  twitter-card:
    image: images/logo-site.png
    card-style: summary_large_image
  
  # --- RECHERCHE (Doit être indenté sous website) ---
  search:
    location: navbar
    type: textbox

  # --- BARRE DE NAVIGATION ---
  navbar:
    title: "Mattéo Lanoë"
    
    background: primary
    # MENU GAUCHE
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: about.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Invited Talks & Conferences"
        href: talks.qmd
      - text: "Socials"
        href: socials.qmd

    # MENU DROITE (ICÔNES)
    right:
      - icon: envelope
        href: mailto:matteo.lanoe@sciencespo.fr
        aria-label: "Mail"
      - icon: twitter-x
        href: https://twitter.com/MatteoLanoe_
        aria-label: "Twitter"
      - icon: clouds
        href: https://bsky.app/profile/matteolanoe.bsky.social
        aria-label: "BlueSky"

# --- PIED DE PAGE ---
  page-footer:
    left: "© 2026 Mattéo Lanoë"
    center: |
      <div class="footer-center-container">
      <div class="footer-address">
      <strong>Mattéo Lanoë</strong><br>
      Centre de Recherche sur les Inégalités Sociales (CRIS)<br>
      Sciences Po, 1 place Saint-Thomas d'Aquin<br>
      75007 Paris, France
      </div>
      <div class="footer-logos">
      <a href="https://www.sciencespo.fr/" target="_blank"><img src="images/logo-sciencespo.png" alt="Sciences Po" class="footer-logo"></a>
      <a href="https://www.ined.fr/" target="_blank"><img src="images/logo-ined1.png" alt="INED" class="footer-logo"></a>
      </div>
      </div>
    right: "Made with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: header.html