---
title: "Research"
---

## PhD Dissertation

**Title:** *When the Virus Strains: Life Course, Dispositions and Illness Trajectories of Post-Acute Infectious Syndromes (provisional).*

My PhD research project lies at the intersection of sociology of health and illness, medical sociology, sociology of socialization and dispositionnalist sociology.

I am interested in the social-biological interactions which produce unequal health and social outcomes. My particular focus is on what’s called ‘post-acute infectious syndrome,’ a subtype of chronic illness and symptoms resulting from the infection of an infectious disease (such as Covid-19, for instance).

My main interest relies on studying how embodied and socialized dispositions are getting used in the health context and how, in turn, the health outcomes shape the late socialization — modeling and modifying the primary one, previously incorporated.

Besides, I also dive into issues related to political science, electoral sociology, sociology of education, and the use of methods (either qualitative or quantitative) for social inquiry.

## Main Interests

-   Socialization and Dispositions
-   Body and Embodiment
-   Social Inequalities in Health : 
    - Sociology of Diseases ; 
    - Sociology of Health and Illness ; 
    - Medical Sociology ; 
-   [Fundamental Cause Theory](https://pubmed.ncbi.nlm.nih.gov/7560851/)
-   Sociology of Chronic Illnesses
-   Social-biological Interactions
-   Social Theory
-   Social Epidemiology

## Publications

:::: {style="margin-bottom: 30px;"}
Hublet, François et **Lanoë, Mattéo**, 2025. "A Tale of Three Cleavages: Quantifying the Role of Social Demarcations in the 2022 French Presidential Election". *Revue française de science politique*, 2025/2 n° 75, p.215-260. [DOI : 10.3917/rfsp.752.0215](https://shs.cairn.info/revue-revue-francaise-de-science-politique-2025-2-page-215?lang=fr)

<details>
<summary>Abstract</summary>

<div>
The 2022 French presidential election unfolded during a phase of political realignment marked by the emergence of a relatively balanced tripolar competition among left-wing, center-right, and far-right parties. To analyze the underlying social and electoral cleavages, we conducted a large-scale, precinct-level quantitative study of socio-demographic variables. While our findings broadly support neo-cleavage theories, they also underscore the enduring explanatory power of socio-economic predictors in shaping electoral behavior. We identify three main cleavage dimensions—socio-economic, educational, and migratory—that produce a system of cross-cutting cleavages among the four main electoral choices: Mélenchon, Macron, Le Pen, and abstention.

---

```bibtex
@article{hublet_lanoe_2025,
 author = {Hublet, François and Lanoë, Mattéo},  title = {A Tale of Three Cleavages: Quantifying the Role of Social Demarcations in the 2022 French Presidential Election},
 journal = {Revue française de science politique},  volume = {75},
 number = {2},  year = {2025},
 pages = {215--260},  doi = {10.3917/rfsp.752.0215},
  url = {[https://shs.cairn.info/revue-revue-francaise-de-science-politique-2025-2-page-215?lang=fr](https://shs.cairn.info/revue-revue-francaise-de-science-politique-2025-2-page-215?lang=fr)}
}
```
</div>
</details>

::::

:::: {style="margin-bottom: 30px;"}
Hublet François, **Lanoë Mattéo**, Schleyer Johanna, "Spelling out the European center-right’s dilemma: Renewal of the Grand coalition or National-Conservative Alliance?", *Groupe d'études géopolitiques*, Jun 2023. [Available online](https://geopolitique.eu/en/2023/06/19/spelling-out-the-european-center-rights-dilemma-renewal-of-the-grand-coalition-or-national-conservative-alliance/)

<details>

<summary>Abstract</summary>

<div>

One year ahead of the next European election, the European center-right and right-wing parties can feel both confident about their success and worried about their future. On the one hand, conservative and nationalist forces are enjoying undeniable momentum. By increasing their overall vote share only slightly, the three political groups ranging from the center-right to the far-right could secure a parliamentary majority, a fact unprecedented in EU history \[...\]

---

```bibtex
@article{hublet_lanoe_schleyer_2023,
  author = {Hublet, François and Lanoë, Mattéo and Schleyer, Johanna},
  title = {Spelling out the European center-right’s dilemma: Renewal of the Grand coalition or National-Conservative Alliance?},
  journal = {Groupe d'études géopolitiques},
  month = {jun},
  year = {2023},
  url = {https://geopolitique.eu/en/2023/06/19/spelling-out-the-european-center-rights-dilemma-renewal-of-the-grand-coalition-or-national-conservative-alliance/}
}
```

</div>

</details>
::::
