---
title: "Presentations"
---

I regularly present my research on **Long Covid, socialization, dispositions, and social-biological interactions**, as well as related work on health inequalities and illness trajectories. My presentations draw on both qualitative and quantitative approaches to social inquiry.

## Seminars

::: {.grid .talk-grid}

::: {.g-col-12 .g-col-md-2}
**May 2026**
:::
::: {.g-col-12 .g-col-md-10 .talk-details}
**Words for Ills: Comment pathologise-t-on un symptôme ?** \
*INED Doctoral Workshop* \
INED, Aubervilliers \
Discussion by Ilana Löwy
:::

::: {.g-col-12 .g-col-md-2}
**Feb 2026**
:::
::: {.g-col-12 .g-col-md-10 .talk-details}
**Comment le SARS-CoV-2 reste sous la peau ? INCORP-19: Infections, Corps et Parcours des malades post-Covid-19** \
*Mortality, Health and Epidemiology Internal Seminar* \
INED, Aubervilliers
:::

::: {.g-col-12 .g-col-md-2}
**Nov 2025**
:::
::: {.g-col-12 .g-col-md-10 .talk-details}
**CRIS Scientific Seminar** \
*Sciences Po, Paris*
:::

:::

## Conference Presentations

::: {.grid .talk-grid}

::: {.g-col-12 .g-col-md-2}
**Nov 2026**
:::
::: {.g-col-12 .g-col-md-10 .talk-details}
**Paths of Declaration and Auto-Diagnosis in Long Covid and its Symptoms: A Multi-Method Study** \
*4th International Conference on Long Covid, Nice* \
Poster presentation \
With Anne Pastorello (epidemiologist, Inserm)
:::

::: {.g-col-12 .g-col-md-2}
**Aug 2026**
:::
::: {.g-col-12 .g-col-md-10 .talk-details}
**The Taming Disease: How Long Covid Crushes Previous Socializations** \
*American Sociological Association Annual Meeting, New York City* \
Sociology of Body and Embodiment Section \
Bodies and Health Rountable
:::

::: {.g-col-12 .g-col-md-2}
**Aug 2025**
:::
::: {.g-col-12 .g-col-md-10 .talk-details}
**Class, Capital, and Chronic Illness: A Dispositionalist Approach to Long Covid Management** \
*American Sociological Association Annual Meeting, Chicago* \
Student Forum Section \
Health and Illness Roundtable
:::

:::